CANNOT_SUBMIT_ON_SUNDAYS = "Cannot submit a claim on Sunday"
INVALID_CLAIM_AMOUNTS = "Invalid claim amount"
AGE_SHOULD_BE_ABOVE_EIGHTEEN = "Age should be greater than 18"
CANNOT_SUBMIT_FOR_FUTURE_DATE= "Cannot submit a claim for future date"
CANNOT_SUBMIT_VEHICLE = "Only car, lorry, bike, scooter, bus are allowed for claim"
INVALID_lICENSE_NUM = "Invalid license number"