# Generated by Django 3.2.5 on 2021-07-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='claim_amount',
            field=models.IntegerField(default=0),
        ),
    ]
