# Generated by Django 3.2.5 on 2021-07-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_rename_claim_amount_claims_claims_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
